android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
# KSP
ksp.useKSP2=true
# 强制启用 YukiHookAPI 对新版 LSPosed (Modern Xposed / API 101+) 的支持
yukihookapi.xposed.module.isEnable = true
yukihookapi.xposed.module.injectApi = 101
